
APPLICATION_ID = "t4WKDKIQROtp4tUHtQRyUOBGAnyTKjMv8fwlzMvB"
REST_API_KEY = "IMTtB88bSsiWhOei0aCGJI3QIRChqUXZYBAXf0aa"
MASTER_KEY = "------------------------"

APPLICATION_ID = "t4WKDKIQROtp4tUHtQRyUOBGAnyTKjMv8fwlzMvB"
REST_API_KEY = "IMTtB88bSsiWhOei0aCGJI3QIRChqUXZYBAXf0aa"
MASTER_KEY = "------------------------"
